# Generated by Django 4.0.10 on 2026-07-12 08:35

import ddcz.models.magic
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ddcz", "0019_fix_empty_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rune",
            name="donor_nick",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="nick_darce", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="rune",
            name="receiver_nick",
            field=ddcz.models.magic.MisencodedCharField(
                db_column="nick_prijemce", max_length=30
            ),
        ),
    ]
